var config = new Object();
config.siteUrl 	= "http://localhost/hyh/";																							//url of the site
config.dir = new Object();																															//directory paths
	config.dir.model = config.siteUrl + "php/model/";																				//model
	config.dir.html = config.siteUrl + "php/html/";																					//html
	config.dir.image = config.siteUrl + "pics/";																						//images
	config.dir.data = "../data/";																														//data
config.file = new Object();																															//files
	config.file.model = new Object();																												//model
		config.file.model.get = config.dir.model + "getFile.php";																//file gets
		config.file.model.users = config.dir.model + "adminUsers.php";													//user model
		config.file.model.activities = config.dir.model + "adminActivities.php";								//activities model
		config.file.model.lists = config.dir.model + "adminLists.php";													//lists model
	config.file.html = new Object();																												//html
		config.file.html.framework = config.dir.html + "adminFramework.html";										//framework
		config.file.html.homepage = config.dir.html + "adminHomePage.html";											//home page
		config.file.html.activities = config.dir.html + "adminActivities.html";									//activities
		config.file.html.healthyMenu = config.dir.html + "adminHealthyMenu.html";								//healthy menu
		config.file.html.activityLists = config.dir.html + "adminActivityLists.html";						//activity lists
	config.file.data = new Object();																												//data
		config.file.data.languages = config.dir.data + "languages.json";												//languages